POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "admin1",
    "password": "123"


}

####

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin2",
    "password": "123"

}

####

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123"

}





####
GET http://localhost:3000/events

####
GET http://localhost:3000/events/2


####
GET http://localhost:3000/registrations/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzEwNDk4Njg1LCJleHAiOjE3MTA1MDIyODV9.hkUngvN8epmiRPi1veQhdE9EIMJ9NphRNjOGl3BSO10

###

GET http://localhost:3000/registrations/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzEwNDk4ODEwLCJleHAiOjE3MTA1MDI0MTB9.CXl-BKY4mU-D9rEPZJY4bKDnv4F55NCokP4sXBRELNI





####
GET http://localhost:3000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzEwNDk4ODEwLCJleHAiOjE3MTA1MDI0MTB9.CXl-BKY4mU-D9rEPZJY4bKDnv4F55NCokP4sXBRELNI



####
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzEwNDk4ODEwLCJleHAiOjE3MTA1MDI0MTB9.CXl-BKY4mU-D9rEPZJY4bKDnv4F55NCokP4sXBRELNI


####
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzEwNDk5NzExLCJleHAiOjE3MTA1MDMzMTF9.tsFaWb23Yrgck9P5AwoKRpCTtrNJ--dTMkTC_pxxk9c



####
POST http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzEwNDk5Mzk4LCJleHAiOjE3MTA1MDI5OTh9.EVqp2xdAMLizkd6PKzTwJjIk4tBP5NxZ5_gW3pDQYTQ
Content-Type: application/json

{
    "username": "prufa",
    "password": "123"

}



####
DELETE http://localhost:3000/users/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzEwNDk5NzExLCJleHAiOjE3MTA1MDMzMTF9.tsFaWb23Yrgck9P5AwoKRpCTtrNJ--dTMkTC_pxxk9c



####
POST http://localhost:3000/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzEwNTAxODcwLCJleHAiOjE3MTA1MDU0NzB9.1VQWoCDPAIAIAw3Yri1seZHZB0P_MrdtpyhE8c4yAS4
Content-Type: application/json

{
    "title": "mitt event2",
    "place": "hja mer",
    "imageURL": "slod",
    "date": "2024-01-23T15:20:53.955Z"
}



####

