POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "admin2",
    "password": "123"


}



####

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123"

}



####
POST http://localhost:3001/teams
Content-Type: application/json

{
    "name": "TeamEgill"
    

}



####
GET http://localhost:3001/events/teamegill


####
GET http://localhost:3000/events

####
GET http://localhost:3000/2





####
DELETE http://localhost:3001/teams/teamegill
Content-Type: application/json

{
    "slug": "TeamEgill"
}


####
PATCH  http://localhost:3001/teams/TeamEgill
Content-Type: application/json

{
    "name": "TeamEgill",
    "description": "Besta lið í heimi"
}




####
GET http://localhost:3000/admin


####
GET http://localhost:3000/users


####
POST  http://localhost:3000/users



####

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123"

}


####
GET http://localhost:3000/users
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzEwNDM0NjE2LCJleHAiOjE3MTA0MzgyMTZ9.hq8CgaUKWxLlSUYpsD8aOfe6sOHmju-Q1w8_OsMbm54


###

